services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api
    env_file:
      - ./apps/api/.env
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: abcde
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
