apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: database-svc
  name: database-svc
spec:
  ports:
    - name: database-svc
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    run: database
  type: ClusterIP
