apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database
  name: database
spec:
  containers:
    - image: postgres:alpine
      name: database
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: DATABASE_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
        - containerPort: 5432
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - nc -z localhost 5432
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - nc -z localhost 5432
        initialDelaySeconds: 10
        periodSeconds: 5
      resources:
        requests:
          cpu: '200m'
          memory: '256Mi'
        limits:
          cpu: '500m'
          memory: '512Mi'
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: ebs-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
